// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace Rdn.Serialization.Metadata
{
    /// <summary>
    /// Contains utilities and combinators acting on <see cref="IRdnTypeInfoResolver"/>.
    /// </summary>
    public static class RdnTypeInfoResolver
    {
        /// <summary>
        /// Combines multiple <see cref="IRdnTypeInfoResolver"/> sources into one.
        /// </summary>
        /// <param name="resolvers">Sequence of contract resolvers to be queried for metadata.</param>
        /// <returns>A <see cref="IRdnTypeInfoResolver"/> combining results from <paramref name="resolvers"/>.</returns>
        /// <exception cref="ArgumentException"><paramref name="resolvers"/> is null.</exception>
        /// <remarks>
        /// The combined resolver will query each of <paramref name="resolvers"/> in the specified order,
        /// returning the first result that is non-null. If all <paramref name="resolvers"/> return null,
        /// then the combined resolver will also return <see langword="null"/>.
        ///
        /// Can be used to combine multiple <see cref="RdnSerializerContext"/> sources,
        /// which typically define contract metadata for small subsets of types.
        /// It can also be used to fall back to <see cref="DefaultRdnTypeInfoResolver"/> wherever necessary.
        /// </remarks>
        public static IRdnTypeInfoResolver Combine(params IRdnTypeInfoResolver?[] resolvers)
        {
            ArgumentNullException.ThrowIfNull(resolvers);

            return Combine((ReadOnlySpan<IRdnTypeInfoResolver?>)resolvers);
        }

        /// <summary>
        /// Combines multiple <see cref="IRdnTypeInfoResolver"/> sources into one.
        /// </summary>
        /// <param name="resolvers">Sequence of contract resolvers to be queried for metadata.</param>
        /// <returns>A <see cref="IRdnTypeInfoResolver"/> combining results from <paramref name="resolvers"/>.</returns>
        /// <remarks>
        /// The combined resolver will query each of <paramref name="resolvers"/> in the specified order,
        /// returning the first result that is non-null. If all <paramref name="resolvers"/> return null,
        /// then the combined resolver will also return <see langword="null"/>.
        ///
        /// Can be used to combine multiple <see cref="RdnSerializerContext"/> sources,
        /// which typically define contract metadata for small subsets of types.
        /// It can also be used to fall back to <see cref="DefaultRdnTypeInfoResolver"/> wherever necessary.
        /// </remarks>
        public static IRdnTypeInfoResolver Combine(params ReadOnlySpan<IRdnTypeInfoResolver?> resolvers)
        {
            var resolverChain = new RdnTypeInfoResolverChain();
            foreach (IRdnTypeInfoResolver? resolver in resolvers)
            {
                resolverChain.AddFlattened(resolver);
            }

            return resolverChain.Count == 1 ? resolverChain[0] : resolverChain;
        }

        /// <summary>
        /// Creates a resolver applies modifications to the metadata generated by the source <paramref name="resolver"/>.
        /// </summary>
        /// <param name="resolver">The source resolver generating <see cref="RdnTypeInfo"/> metadata.</param>
        /// <param name="modifier">The delegate modifying non-null <see cref="RdnTypeInfo"/> results.</param>
        /// <returns>A new <see cref="IRdnTypeInfoResolver"/> instance applying the modifications.</returns>
        /// <remarks>
        /// This method is closely related to <see cref="DefaultRdnTypeInfoResolver.Modifiers"/> property
        /// extended to arbitrary <see cref="IRdnTypeInfoResolver"/> instances.
        /// </remarks>
        public static IRdnTypeInfoResolver WithAddedModifier(this IRdnTypeInfoResolver resolver, Action<RdnTypeInfo> modifier)
        {
            ArgumentNullException.ThrowIfNull(resolver);
            ArgumentNullException.ThrowIfNull(modifier);

            return resolver is RdnTypeInfoResolverWithAddedModifiers resolverWithModifiers
                ? resolverWithModifiers.WithAddedModifier(modifier)
                : new RdnTypeInfoResolverWithAddedModifiers(resolver, new[] { modifier });
        }

        /// <summary>
        /// Gets a resolver that returns null <see cref="RdnTypeInfo"/> for every type.
        /// </summary>
        internal static IRdnTypeInfoResolver Empty { get; } = new EmptyRdnTypeInfoResolver();

        /// <summary>
        /// Indicates whether the metadata generated by the current resolver
        /// are compatible with the run time specified <see cref="RdnSerializerOptions"/>.
        /// </summary>
        internal static bool IsCompatibleWithOptions(this IRdnTypeInfoResolver? resolver, RdnSerializerOptions options)
            => resolver is IBuiltInRdnTypeInfoResolver bir && bir.IsCompatibleWithOptions(options);
    }

    /// <summary>
    /// A <see cref="IRdnTypeInfoResolver"/> that returns null for all inputs.
    /// </summary>
    internal sealed class EmptyRdnTypeInfoResolver : IRdnTypeInfoResolver, IBuiltInRdnTypeInfoResolver
    {
        public RdnTypeInfo? GetTypeInfo(Type type, RdnSerializerOptions options) => null;
        public bool IsCompatibleWithOptions(RdnSerializerOptions _) => true;
    }

    /// <summary>
    /// Implemented by the built-in converters to avoid rooting
    /// unused resolver dependencies in the context of the trimmer.
    /// </summary>
    internal interface IBuiltInRdnTypeInfoResolver
    {
        /// <summary>
        /// Indicates whether the metadata generated by the current resolver
        /// are compatible with the run time specified <see cref="RdnSerializerOptions"/>.
        /// </summary>
        bool IsCompatibleWithOptions(RdnSerializerOptions options);
    }
}
