package com.rdn.intellij.highlighting

import com.intellij.openapi.editor.DefaultLanguageHighlighterColors as Default
import com.intellij.openapi.editor.colors.TextAttributesKey

object RdnColors {
    val KEYWORD = TextAttributesKey.createTextAttributesKey("RDN_KEYWORD", Default.KEYWORD)
    val NUMBER = TextAttributesKey.createTextAttributesKey("RDN_NUMBER", Default.NUMBER)
    val BIGINT = TextAttributesKey.createTextAttributesKey("RDN_BIGINT", Default.NUMBER)
    val STRING = TextAttributesKey.createTextAttributesKey("RDN_STRING", Default.STRING)
    val STRING_ESCAPE = TextAttributesKey.createTextAttributesKey("RDN_STRING_ESCAPE", Default.VALID_STRING_ESCAPE)
    val STRING_INVALID_ESCAPE = TextAttributesKey.createTextAttributesKey("RDN_STRING_INVALID_ESCAPE", Default.INVALID_STRING_ESCAPE)
    val OBJECT_KEY = TextAttributesKey.createTextAttributesKey("RDN_OBJECT_KEY", Default.INSTANCE_FIELD)
    val AT_SIGN = TextAttributesKey.createTextAttributesKey("RDN_AT_SIGN", Default.METADATA)
    val DATE_PART = TextAttributesKey.createTextAttributesKey("RDN_DATE_PART", Default.METADATA)
    val TIME_PART = TextAttributesKey.createTextAttributesKey("RDN_TIME_PART", Default.NUMBER)
    val MILLIS_PART = TextAttributesKey.createTextAttributesKey("RDN_MILLIS_PART", Default.NUMBER)
    val TIMEZONE = TextAttributesKey.createTextAttributesKey("RDN_TIMEZONE", Default.KEYWORD)
    val UNIX_TIMESTAMP = TextAttributesKey.createTextAttributesKey("RDN_UNIX_TIMESTAMP", Default.NUMBER)
    val DURATION_P = TextAttributesKey.createTextAttributesKey("RDN_DURATION_P", Default.METADATA)
    val DURATION_NUMBER = TextAttributesKey.createTextAttributesKey("RDN_DURATION_NUMBER", Default.NUMBER)
    val DURATION_UNIT = TextAttributesKey.createTextAttributesKey("RDN_DURATION_UNIT", Default.KEYWORD)
    val DURATION_T = TextAttributesKey.createTextAttributesKey("RDN_DURATION_T", Default.METADATA)
    val BINARY_PREFIX = TextAttributesKey.createTextAttributesKey("RDN_BINARY_PREFIX", Default.KEYWORD)
    val BINARY_CONTENT = TextAttributesKey.createTextAttributesKey("RDN_BINARY_CONTENT", Default.STRING)
    val BINARY_INVALID_CHAR = TextAttributesKey.createTextAttributesKey("RDN_BINARY_INVALID_CHAR", Default.INVALID_STRING_ESCAPE)
    val MAP_KEYWORD = TextAttributesKey.createTextAttributesKey("RDN_MAP_KEYWORD", Default.KEYWORD)
    val SET_KEYWORD = TextAttributesKey.createTextAttributesKey("RDN_SET_KEYWORD", Default.KEYWORD)
    val REGEXP_BODY = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_BODY", Default.STRING)
    val REGEXP_ESCAPE = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_ESCAPE", Default.VALID_STRING_ESCAPE)
    val REGEXP_CHAR_CLASS_ESCAPE = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_CHAR_CLASS_ESCAPE", Default.VALID_STRING_ESCAPE)
    val REGEXP_QUANTIFIER = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_QUANTIFIER", Default.KEYWORD)
    val REGEXP_ANCHOR = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_ANCHOR", Default.KEYWORD)
    val REGEXP_ALTERNATION = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_ALTERNATION", Default.KEYWORD)
    val REGEXP_DOT = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_DOT", Default.KEYWORD)
    val REGEXP_GROUP = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_GROUP", Default.PARENTHESES)
    val REGEXP_SPECIAL = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_SPECIAL", Default.METADATA)
    val REGEXP_CHAR_CLASS = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_CHAR_CLASS", Default.BRACKETS)
    val REGEXP_FLAGS = TextAttributesKey.createTextAttributesKey("RDN_REGEXP_FLAGS", Default.METADATA)
    val BRACES = TextAttributesKey.createTextAttributesKey("RDN_BRACES", Default.BRACES)
    val BRACKETS = TextAttributesKey.createTextAttributesKey("RDN_BRACKETS", Default.BRACKETS)
    val PARENS = TextAttributesKey.createTextAttributesKey("RDN_PARENS", Default.PARENTHESES)
    val COMMA = TextAttributesKey.createTextAttributesKey("RDN_COMMA", Default.COMMA)
    val COLON = TextAttributesKey.createTextAttributesKey("RDN_COLON", Default.SEMICOLON)
    val ARROW = TextAttributesKey.createTextAttributesKey("RDN_ARROW", Default.OPERATION_SIGN)
    val BAD_CHARACTER = TextAttributesKey.createTextAttributesKey("RDN_BAD_CHARACTER", Default.INVALID_STRING_ESCAPE)
}
