package com.rdn.intellij.psi

import com.intellij.psi.tree.IElementType
import com.intellij.psi.tree.IFileElementType
import com.rdn.intellij.RdnLanguage

class RdnElementType(debugName: String) : IElementType(debugName, RdnLanguage)

/**
 * Manually-defined element types that are NOT generated by GrammarKit.
 * GrammarKit generates PSI element types (OBJECT, ARRAY, MAP, etc.) in [RdnTypes].
 */
object RdnElementTypes {
    @JvmField val FILE = IFileElementType(RdnLanguage)
}
